---

name: Sample Playbook
stages:
- name: s1
  request:
    url: https://server/posts/1
    method: GET
    query:
      foo: "bar"
    headers:
      content-type: application/json
  response:
    code: 200
    body:
      id: 1
- name: s2
  request:
    url: https://server/posts
    method: POST
    json:
      title: "hello"
      body: "world"
      foo:
        bar: "baz"
    headers:
      content-type: application/json
  response:
    code: 200
    body:
      total: !exp total > 0
